#!/usr/bin/env node
/* build-browser-versions.js builds a browserify version and a minimal browser version */
var fs = require('fs'),
    path = require('path'),
    spawn = require('cross-spawn').spawn;

// Modules to be included in the minimal browser version
var submodules = [
  'Util',
  'Jison',
  'Parser',
  'Validator',
  'Loader',
  'Writer',
];


/* Set up paths */
var rootPath = path.join(__dirname, '../'),
    sourcePath = path.join(rootPath, 'lib/'),
    destinationPath = path.join(rootPath, 'browser/'),
    uglifyjsPath = path.join(rootPath, 'node_modules/.bin/uglifyjs'),
    browserifyPath = path.join(rootPath, 'node_modules/.bin/browserify');

if (!fs.existsSync(destinationPath))
  fs.mkdirSync(destinationPath);


/* Create minimal browser version */

var scriptFile = destinationPath + 'shex-browser.js',
    minifiedFile = destinationPath + 'shex-browser.min.js',
    script = fs.createWriteStream(scriptFile, { encoding: 'utf8' });

// Add license information
var package = JSON.parse(fs.readFileSync(path.join(rootPath, 'package.json')));
script.write('/** @license MIT - shex.js ' + package.version +
             ' (browser build) - ©Eric Prud\'hommeaux */\n');

// Start main wrapping function
script.write('(function (ShEx) {\n');

// Add modules
submodules.forEach(function (name) {
  var submodule = fs.readFileSync(sourcePath + 'ShEx' + name + '.js', { encoding: 'utf8' });
  // Remove imports
  submodule = submodule.replace(/require\(['"]\.\/ShEx([^'"]+)['"]\)/g, 'ShEx.$1');
  // Replace exports by assignments on the ShEx object
  submodule = submodule.replace(/module.exports/g, '\nShEx.' + name);
  script.write('(function () {\n' + submodule + '\n})();\n');
});

// End and execute main wrapping function
script.write('})(typeof exports !== "undefined" ? exports : this.ShEx = {});\n');
script.end(function () {
  console.log('minimal browser version written to', scriptFile);
  // Write minified file
  // console.log(uglifyjsPath,
  //                      [ scriptFile, '--comments', '-m', '-c', '-o', minifiedFile ],
  //                      { stdio: 'inherit' });
  var minifier = spawn(uglifyjsPath,
                       [ scriptFile, '--comments', '-m', '-c', '-o', minifiedFile ],
                       { stdio: 'inherit' });
  minifier.on('exit', function () {
    console.log('minimal browser version (minified) written to', minifiedFile);
  });
});


/* Build browserify version */

    console.log(browserifyPath,
                [ rootPath + 'shex.js', '-s', 'shex', '-t', 'es6-templates', '-t', 'es6-arrow-function', '-o', browserifiedFile ].join(" "));
var browserifiedFile = destinationPath + 'shex-browserify.js',
    browserify = spawn(browserifyPath,
                       [ rootPath + 'shex.js', '-s', 'shex', '-t', 'es6-templates', '-t', 'es6-arrow-function', '-o', browserifiedFile ],
                       { stdio: 'inherit' });
browserify.on('exit', function () {
  console.log('browserify version written to', browserifiedFile);
});
