# generated by tools/makeMake.js 2023-01-15T22:59:24.429Z

# @shexjs/eval-validator-api
packages/eval-validator-api/lib/validator-api.js: packages/eval-validator-api/src/validator-api.ts packages/eval-validator-api/package.json packages/eval-validator-api/tsconfig.json
	(cd packages/eval-validator-api && tsc)

# @shexjs/neighborhood-api
packages/neighborhood-api/lib/neighborhood-api.js: packages/neighborhood-api/src/neighborhood-api.ts packages/neighborhood-api/package.json packages/neighborhood-api/tsconfig.json
	(cd packages/neighborhood-api && tsc)

# @shexjs/validator
packages/shex-validator/lib/shex-validator.js packages/shex-validator/lib/shex-xsd.js: packages/shex-validator/src/shex-validator.ts packages/shex-validator/src/shex-xsd.ts packages/neighborhood-api/lib/neighborhood-api.js packages/eval-validator-api/lib/validator-api.js packages/shex-validator/package.json packages/shex-validator/tsconfig.json
	(cd packages/shex-validator && tsc)

ALL: packages/eval-validator-api/lib/validator-api.js packages/neighborhood-api/lib/neighborhood-api.js packages/shex-validator/lib/shex-validator.js packages/shex-validator/lib/shex-xsd.js

