module.exports = {
  help:			0,
  dry_run:		0,
  shape_test_pass:	0,
  shape_test_fail:	1,
  bad_argument:		2,
  graph_match_pass:	0,
  graph_match_fail:	3,
  val_match_pass:	0,
  val_match_fail:	4,
  json_pass:		0,
  shexc_pass:		0,
  term_not_found:	5,
  resource_not_found:	6,
  file_not_found:	7,
  manifest_error:	8,
  manifest_not_found:	9,
  unspecified_error:	99,
}
