#!/usr/bin/env node
/** lib/prelude.wat as a TypeScript module, so prelude() needs no
 * filesystem: the browser bundle (webpack.config.js) has no Fs, and the
 * compiled lib reads the same constant.  Run by `npm run build`; the .wat
 * stays the file to edit. */
"use strict";
const Fs = require("fs");
const Path = require("path");
const wat = Fs.readFileSync(Path.join(__dirname, "../lib/prelude.wat"), "utf8");
Fs.writeFileSync(Path.join(__dirname, "../src/prelude-wat.ts"),
  "/** GENERATED by tools/gen-prelude.js from lib/prelude.wat -- edit there. */\n"
  + "export const preludeWat: string = " + JSON.stringify(wat) + ";\n");
console.log("src/prelude-wat.ts <- lib/prelude.wat (" + wat.length + " bytes)");
