#!/usr/bin/env node

// Parse arguments
var args = process.argv.slice(2);
if (args.length < 1) {
  console.error('usage: partition schema.shex');
  return process.exit(1);
}

var fs = require('fs');
var ShExParser = require('../lib/ShExParser').Parser;
var ShExUtil = require('../lib/ShExUtil');

// Parse and display the schema
var shex = fs.readFileSync(args[0]).toString();
var parseTree = new ShExParser().parse(shex);
var deps = ShExUtil.getDependencies(parseTree);
console.log('%s', JSON.stringify(deps, null, '  '));
